name: Deploy # workflow name

on:

jobs:
  build: # job1 id
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: A job to deploy blog.
    steps:
    - name: Checkout # step1 获取 hexo 源码
      uses: actions/checkout@v1 # 使用 actions/checkout@v1
      with: # 条件
        submodules: true # Checkout private submodules(themes or something else). 当有子模块时时，同步子模块

    # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.) 根据 package-lock.json 压缩缓存 node_modules，不用每次下载，使用时解压，可以加快工作流的执行过程，超过 7 天没有使用将删除压缩包。
    - name: Cache node modules # step2
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # 使用 Hexo 项目的 package-lock.json 安装、缓存 node_moudules
        restore-keys: |
          ${{ runner.os }}-node-
          
    - name: Install Dependencies # step3
      if: steps.cache.outputs.cache-hit != 'true' # 如果没有缓存 node_modules
      run: npm install # 根据 package.json 在 node_modules 下载相关包（依赖）

    # Deploy hexo blog website.
    - name: Deploy # step4
      id: deploy
      uses: deppwang/hexo-action@v1.0.0
      with:
        deploy_key: ${{ secrets.HEXO_DEPLOY_KEY }} 
        user_name: hr1ycfl # 自定义
        user_email: oneal.wang@foxmail.com # 自定义
        
        
        
        
